version: '3'
services:
  db:
    image: mysql:8.0
    platform: linux/x86_64

    env_file: ./api/mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - backend

  app:
    # 起動するイメージを指定（ここではNode.js v12の公式イメージ）
    image: node:12
    container_name: recordapi
    # 環境変数を設定
    environment:
      - DEBUG=app:*

    tty: true

    # ホスト側のポート:コンテナのポート
    ports:
      - '3000:3000'

    # ソースコードを格納するフォルダをマウント
    #（ホスト側の./srcをコンテナの/appにマウント）
    volumes:
      - ./api/src:/project

    # 起動時のカレントフォルダを指定
    working_dir: /project

    # 起動後に実行するコマンドを指定
    command: npm run dev

    networks:
      - backend
      - frontend
    depends_on:
      - db

  front:
    # image: react
    container_name: recorduser
    build: 
      context: .
      dockerfile: ./docker/user/Dockerfile_front
    environment:
      - NODE_ENV=development
    volumes:
      - ./user/src/front:/app
    working_dir: /app
    tty: true
    ports:
     - 8088:8088

    # 起動後に実行するコマンドを指定
    command: npm run start
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  mysqldata:

